添加注释和导出接口跟事件
GroupMountain/GMLIB-LegacyRemoteCallApi pull request #29
Opened 2024-06-23 18:17 UTC by zimuya4153

- 添加jsdoc注释和d.ts补全文件
- 修改getBlockRuntimeId接口，使其支持填写特殊值
- 添加getBlockLightEmission，getGameRules，applyEnchant，removeEnchants，hasEnchant，getEnchantLevel，getEnchantNameAndLevel接口
- 导出事件onEntityChangeDimAfter，DragonRespawn，ProjectileTryCreate，ProjectileCreate

2024-06-25 09:56 UTC, killcerr commented
等GMLIB适配最新版LL吧，现在无法构建

2024-06-26 18:02 UTC, KobeBryant114514 requested changes
附魔用typename不要用id。
Event写的什么玩意，完全不符合event规范，不知道写的啥玩意，这类型强转也不知道在转啥。还有就是event请PR到gmlib里面去。
getMaxPlayers你确定能用吗，明显是错的。

2024-07-18 14:02 UTC, killcerr commented on lib/EventAPI-JS.js
>  function getNextEventId() {
这种函数并不是给脚本插件编写者使用的，不需要解释

2024-07-18 14:03 UTC, killcerr commented on lib/EventAPI-JS.d.ts
> +        event: "onItemTrySpawn",
这是否是写错了

2024-07-18 14:05 UTC, killcerr commented on lib/BEPlaceholderAPI-JS.js
> +String.prototype.hashCode = function () {
hashCode这个函数有什么用

2024-07-18 14:07 UTC, zimuya4153 commented on lib/BEPlaceholderAPI-JS.js
> +String.prototype.hashCode = function () {
防止匿名函数，但不能真随机生成一个，不然就会导致同一个函数，获取名字结果不一样。为了和下面的代码适配

2024-07-18 14:07 UTC, killcerr commented on lib/GMLIB_API-JS.d.ts
> +    /** 获取存档种子号 */
"获取存档种子"即可

2024-07-18 14:08 UTC, killcerr commented on lib/GMLIB_API-JS.d.ts
> +        /** 方块的命名空间 */
这个不应该是命名空间吧

2024-07-18 14:17 UTC, killcerr commented on lib/GMLIB_API-JS.js
> +LLSE_Item.prototype.canDestroyInCreative =
这个有测试过吗

2024-07-18 14:19 UTC, zimuya4153 commented on lib/GMLIB_API-JS.js
> +LLSE_Item.prototype.canDestroyInCreative =
有，可用

2024-07-18 14:23 UTC, killcerr commented on lib/GMLIB_API-JS.js
> +LLSE_Player.prototype.getArmorValue =
这个是否有错误

2024-07-18 14:23 UTC, zimuya4153 commented on lib/GMLIB_API-JS.js
> +LLSE_Player.prototype.getArmorValue =
没有，已测试

2024-07-18 14:51 UTC, zimuya4153 commented on lib/GMLIB_API-JS.d.ts
> +        /** 合成表摆放方式，数组元素为字符串 */
已改

2024-07-18 14:56 UTC, harry-xi commented on lib/GMLIB_API-JS.d.ts
> +    get(
当默认值与返回值类型一致时，使用泛型以提供更好的类型检查

2024-07-18 15:05 UTC, zimuya4153 commented on lib/GMLIB_API-JS.d.ts
> +    get(
已改

2024-07-18 15:06 UTC, harry-xi commented on lib/BEPlaceholderAPI-JS.js
> +String.prototype.hashCode = function () {
贸然更改内置类型的原型链不是一个好选择，建议考虑替代方案。

2024-07-20 14:25 UTC, killcerr approved these changes

2024-08-01 13:46 UTC, killcerr submitted a review, later dismissed

2024-08-01 14:16 UTC, killcerr commented
请设置action的xmake版本为2.9.3

2024-08-03 14:06 UTC, merged